rest_controllers:
    resource: ../../src/UI/Http/Rest/Controller/
    type: annotation
web_controllers:
    resource: ../../src/UI/Http/Web/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
